# roles/launch_database/tasks/main.yml
---
- name: Create Docker volume 'db-volume'
  community.docker.docker_volume:
    name: db-volume
    state: present

- name: Launch database container
  community.docker.docker_container:
    name: database
    image: lesliemad/tp-devops-database
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db   
      POSTGRES_USER: usr 
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: my-network
    state: started
    restart_policy: always